Improved some of the scripts

diff --git a/bash/bin/run_all_links b/bash/bin/run_all_links
--- a/bash/bin/run_all_links
+++ b/bash/bin/run_all_links
@@ -2,14 +2,42 @@
 # Script made by Adrian Chmiel (chmieladr)
 
 # Launches all the links provided in 'links.txt' file
-# Replace the links in the file provided as an example with your own ones!
-# 'links.txt' file needs to be in the same directory as the script!
+# (or any other given file) in the default browser
+# Feel free to replace the links in the file provided as an example with your own ones!
+# 'links.txt' file needs to be in the same directory as the script
+# (if you want to use it without providing location argument)!
+
+# Determine the file
+if [ $# -eq 0 ] ; then
+    # Use default 'links.txt' file
+    txt=links.txt
+elif [ $# -eq 1 ] ; then
+    # Show help message
+    if [[ "$1" == "-?" || "$1" == "-h" ]]; then
+        echo "Usage: $0 [file]"
+        echo "If no file is provided, the script will look for 'links.txt' in the current directory."
+        echo "Additional arguments will be ignored."
+        exit 0
+    fi
+
+    # Check if the file exists
+    if [ ! -f $1 ] ; then
+        echo "File not found!"
+        exit 1
+    fi
+
+    txt=$1
+else
+    # Ignore additional arguments
+    txt=$1
+    echo "More than one argument provided! Using the first one: $1"
+fi
 
 # Read the links from the file and open each one
 while IFS= read -r link; do
     xdg-open "$link"
     echo "Launching $link"
-done < links.txt
+done < $txt
 
 # Confirmation message
 echo "All links have been opened!"
